version: "3.7"

services:

  nginx:
    container_name: ${APP_NAME}-nginx
    restart: always
    image: nginx:latest
    ports:
      - ${PROJECT_HTTP_PORT}:80
    volumes:
      - ${ROOT_DIR}:/var/www
      - ./docker/nginx/app.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - app-network

  app:
    container_name: ${APP_NAME}-app
    restart: always
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    image: ${APP_NAME}
    volumes:
      - ${ROOT_DIR}:/var/www
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    networks:
      - app-network

  mysql:
    container_name: ${APP_NAME}-mysql
    image: mysql:latest
    restart: always
    ports:
        - ${MYSQL_PORT}:3306
    environment:
        - MYSQL_USER=${MYSQL_USER}
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
        - /docker/.data/mysql:/var/lib/mysql
    networks:
      - app-network

  redis:
    container_name: ${APP_NAME}-redis
    restart: always
    image: redis:3
    ports:
      - ${REDIS_PORT}:6379
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: ${APP_NAME}-phpmyadmin
    networks:
        - app-network
    links:
        - mysql:mysql
    ports:
        - ${PHPMYADMIN_PORT}:80
    environment:
        - FILE_UPLOAD=${PHPMYADMIN_FILE_UPLOAD}
        - UPLOAD_LIMIT=${PHPMYADMIN_UPLOAD_LIMIT}
        - MEMORY_LIMIT=${PHPMYADMIN_MEMORY_LIMIT}
        - POST_MAX_SIZE=${PHPMYADMIN_POST_MAX_SIZE}
        - MAX_EXECUTION_TIME=${PHPMYADMIN_MAX_EXECUTION_TIME}
        - PMA_ARBITARY=${PHPMYADMIN_PMA_ARBITARY}
        - PMA_HOST=mysql

# Docker Networks
networks:
  app-network:
    driver: bridge

